src/catalogue/urls.py
from django.urls import path, re_path
from . import views



app_name = 'catalogue'


urlpatterns = [
    path('',  views.AboutView.as_view(), name='about'),
    path('stores/',  views.IndexView.as_view(), name='stores'),
    path('test/',  views.CollectionView.as_view(), name='collection'),
    path('collection/',  views.TestView.as_view(), name='test'),
    path('catalogue/',  views.CatalogueView.as_view(), name='catalogue'),

    path('deals/', views.DealsView.as_view(), name='deals'),
    path('franquicia/', views.FranquiciaView.as_view(), name='franquicia'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('detail/',  views.getProduct, name='detail'),
    path('contactme/',  views.contact, name='contact_me'),
    path('request/',  views.request, name='request_me'),


]

src/tico/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "Tico-shoes Admin"
admin.site.site_title = "Tico-shoes Admin"
admin.site.index_title = "Панель администратора"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalogue.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

src/catalogue/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from versatileimagefield.fields import PPOIField, VersatileImageField
import django_filters

CONTACT_CHOICES = (
    ('Непрочитанная', 'Непрочитанная'),
    ('В процессе', 'В процессе'),
    ('Завершенная', 'Завершенная'),

)

SEX_CHOICES = (
    ('Мальчики', 'Мальчики'),
    ('Девочки', 'Девочки'),
    ('Унисекс', 'Унисекс'),

)

TAG_CHOICES = (
    ('New', 'New'),
    ('Хит', 'Хит'),
    ('Sale', 'Sale'),
)


class Contact(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    content = models.TextField(blank=True)
    status = models.CharField(choices=CONTACT_CHOICES, max_length=20, verbose_name=u"Статус", default="Непрочитанная")
    created_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return self.name


class Request(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    content = models.TextField(blank=True)
    status = models.CharField(choices=CONTACT_CHOICES, max_length=20, verbose_name=u"Статус", default="Непрочитанная")
    created_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        verbose_name = 'Франшиза'
        verbose_name_plural = 'Франшизы'

    def __str__(self):
        return self.name


class Material(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

    def __str__(self):
        return self.name


class Color(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = 'Цвет'
        verbose_name_plural = 'Цвета'

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = 'Производитель'
        verbose_name_plural = 'Производители'

    def __str__(self):
        return self.name


class Year(MPTTModel):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=True, db_index=True)
    slug = models.SlugField(unique=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE, )

    image = VersatileImageField(
        'Image',
        upload_to='images/',
        width_field='width',
        height_field='height',
        ppoi_field='ppoi',
        blank=True
    )
    height = models.PositiveIntegerField(
        'Image Height',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Image Width',
        blank=True,
        null=True
    )
    ppoi = PPOIField(
        'Image PPOI'
    )

    _metadata = {
        'description': 'description',
    }

    class Meta:
        verbose_name = 'Коллекция'
        verbose_name_plural = 'Коллекции'
        ordering = ['-created_at']

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

    def get_image(self):
        print("Image")
        return self.image


class ProductQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self.db)

    def all(self):
        return self.get_queryset().active()


class Product(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=u"Название")
    slug = models.SlugField(unique=True)
    manufacturer = models.ForeignKey(Manufacturer, related_name='manufacturers', on_delete=models.CASCADE,
                                     verbose_name=u"Производитель")
    sex = models.CharField(choices=SEX_CHOICES, max_length=20, verbose_name=u"Пол")
    content = models.TextField(blank=True, verbose_name=u"Описание")
    color = models.ForeignKey(Color, related_name='color', on_delete=models.CASCADE,
                              verbose_name=u"Цвет")
    material_top = models.ForeignKey(Material, related_name='top', on_delete=models.CASCADE,
                                     verbose_name=u"Материал верха")
    material_bottom = models.ForeignKey(Material, related_name='bottom', on_delete=models.CASCADE,
                                        verbose_name=u"Материал подкладки")

    size = models.CharField(max_length=50, verbose_name=u"Размерный ряд")
    year = models.ForeignKey(Year, related_name='years', on_delete=models.CASCADE, verbose_name=u"Год")

    tag = models.CharField(blank=True, choices=TAG_CHOICES, max_length=20, verbose_name=u"Тэг")

    is_active = models.BooleanField(default=True, verbose_name=u"Активность")

    created_at = models.DateTimeField(auto_now=True, db_index=True)
    updated_at = models.DateTimeField(auto_now_add=True, db_index=True)

    objects = ProductManager()

    class Meta:
        ordering = ['-name']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    @property
    def get_images_url(self):
        return self.images.all()


    def get_first_image(self):
        images = list(self.images.all())
        return images[0].image if images else None

    def get_json(self):
        return {'name': self.name, 'manufacturer': self.manufacturer.name,
                'sex': self.sex, 'content': self.content, 'color': self.color.name,
                'material_top': self.material_top.name, 'material_bottom': self.material_bottom.name,
                'size': self.size, 'year': self.name, 'tag': self.tag
                }


class ProductFilter(django_filters.FilterSet):
    sex = django_filters.CharFilter(field_name='sex', lookup_expr='iexact')
    year = django_filters.NumberFilter(field_name='category', lookup_expr='isnull')

    class Meta:
        model = Product
        fields = ['sex', 'year']

    def my_custom_filter(self, queryset, sex__in):
        return queryset.filter(**{
            sex__in: ["Мальчики"],
        })


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, related_name='images', on_delete=models.CASCADE)

    image = VersatileImageField(
        'Image',
        upload_to='images/',
        width_field='width',
        height_field='height',
        ppoi_field='ppoi'
    )
    height = models.PositiveIntegerField(
        'Высота',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Ширина',
        blank=True,
        null=True
    )
    ppoi = PPOIField(
        'Image PPOI'
    )

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

    def get_ordering_queryset(self):
        return self.product.images.all()


class Deals(models.Model):
    name = models.CharField(max_length=20)
    content = models.TextField(blank=True, verbose_name=u"Описание акции")
    created_at = models.DateTimeField(auto_now=True, db_index=True)

    image = VersatileImageField(
        'Изображение',
        upload_to='images/',
        width_field='width',
        height_field='height',
        ppoi_field='ppoi',
        blank=True
    )
    height = models.PositiveIntegerField(
        'Высота',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Ширина',
        blank=True,
        null=True
    )
    ppoi = PPOIField(
        'Image PPOI'
    )

    class Meta:
        verbose_name = 'Акция'
        verbose_name_plural = 'Акции'

    def get_image(self):
        return self.image if self.image else None

    def __str__(self):
        return self.name

src/catalogue/views.py
from django.views.generic import ListView, TemplateView
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, TemplateView
from django.shortcuts import render

from .models import Product, Year, Deals, Contact, Request, ProductFilter
from django.http import HttpResponse
import json
from django.core import serializers

@csrf_exempt
def contact(request):
    if request.method == "POST" and request.is_ajax():
        name = request.POST['name']
        email = request.POST['email']
        content = request.POST['content']

        contact = Contact(name=name, email=email, content= content)
        contact.save()
        status = 200
        return HttpResponse(status)

    else:
        print("ERRROR")
        status = 500
        return HttpResponse(status)


@csrf_exempt
def request(request):
    print("data = ",request)
    if request.method == "POST" and request.is_ajax():
        name = request.POST['name']
        email = request.POST['email']
        content = request.POST['content']

        request = Request(name=name, email=email, content= content)
        request.save()
        status = 200
        return HttpResponse(status)

    else:
        print("ERRROR")
        status = 500
        return HttpResponse(status)



class ContactView(TemplateView):
    template_name = "contact.html"
    def get_context_data(self, **kwargs):
        context = super(ContactView, self).get_context_data(**kwargs)
        context['active'] = "Contact"
        return context




class IndexView(TemplateView):
    # model = Product
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['active'] = "Stores"
        return context



class AboutView(TemplateView):
    # model = Product
    template_name = "about.html"

    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context['active'] = "About"
        return context



class CollectionView(TemplateView):
    model = Year
    template_name = "collection.html"
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super(CollectionView, self).get_context_data(**kwargs)
        context['active'] = "Collection"
        root = Year.objects._mptt_filter(parent=None)
        object_list = Year.objects.all().get_descendants(include_self=True).filter(level=1)
        context['years'] = root
        context['list'] = object_list
        # print("Roots", root)
        # context.items()
        print("content", context)
        return context


class CatalogueView(ListView):
    model = Product

    template_name = "catalogue.html"
    context_object_name = 'products'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(CatalogueView, self).get_context_data(**kwargs)
        context.items()
        context['active'] = "Collection"

        return context

class TestView(ListView):
    model = Product

    template_name = "test.html"
    context_object_name = 'products'
    paginate_by = 4




    def get_context_data(self, **kwargs):
        context = super(TestView, self).get_context_data(**kwargs)
        context.items()
        data = self.request.GET

        cat = data.getlist('categories[]')
        gen = data.getlist('gender[]')
        print(gen)

        context['nodes'] = Year.objects.all()
        context['active'] = "Collection"

        gender = []

        if '-1' in gen:
            gender.append("Мальчики")
            # gender.append("Унисекс")
        if '-2' in gen:
            gender.append("Девочки")
            # gender.append("Унисекс")
        if '-3' in gen:
            gender.append("Унисекс")

        if gen ==[] and cat == []:
            gender = ["Мальчики", "Девочки", "Унисекс"]
            qs = Product.objects.all()
        else:
            qs = Product.objects.all().filter(sex__in=gender).filter(year__id__in=cat)
        context["object_list"] = qs
        context["gender"] = gender



        # f = ProductFilter(queryset=Product.objects.all()).qs
        # print("F", f)
        # return render(request, 'my_app/template.html', {'filter': f})


        return context




def getProduct(request):
    print(request)
    if request.method == "GET":
        print(request)
        slug = request.GET.get('slug')
        product = Product.objects.get(slug=slug)

        json = product.get_json()
        images = product.get_images_url
        pic = []
        for img in images:
            pic.append(img.image.url)
        json["pic"] = pic

        return JsonResponse(json,  safe=True)
        # result = serializers.serialize('json', [product ])
        # return HttpResponse(result[1:-1], content_type='application/json; charset=UTF-8',
        #                     status=200)
    else:
        return JsonResponse(data={'success': False,
                                  'errors': 'No matching items found'})




class DealsView(ListView):
    model = Deals
    template_name = "deals.html"
    context_object_name = 'deals'

    def get_context_data(self, **kwargs):
        context = super(DealsView, self).get_context_data(**kwargs)
        object_list = Deals.objects.all()
        context['list'] = object_list
        context['active'] = "Deals"
        print(context['list'])
        return context



class FranquiciaView(TemplateView):
    # model = Product
    template_name = "franquicia.html"

    def get_context_data(self, **kwargs):
        context = super(FranquiciaView, self).get_context_data(**kwargs)
        context['active'] = "Franquicia"
        return context

src/catalogue/templates/catalogue.html
{% extends "base.html" %}
{% load static %}

{% load thumbnail %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
</head>
<body class="">



{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/single_styles.css' %}">
{#<link rel="stylesheet" type="text/css" href="{% static 'css/single_responsive.css' %}">#}
{#<link rel="stylesheet" type="text/css" href="{% static 'css/categories_responsive.css' %}">#}


<div class="container contact_container">


{#    <div class="container collection_container " style="background-image:url({% static 'images/background1.png' %})">#}
{#        <div class="row text-center" style="height: 100%">#}
{#            {% for year in years %}#}
{#            <div class="col-lg-3 col-md-6 col-sm-6 d-i-b collection_year_text" style="margin: auto;">#}
{#               <a href="/"> <div class="collection_year">{{ year.year }} </div></a>#}
{#            </div>#}
{#            {% endfor %}#}
{#        </div>#}
{#    </div>#}



    <div class="product-grid">

    {% for object in object_list %}
        <div class="product-item">
        <div class="product ">
            <div class="product_image">
                <img src="{{ object.get_first_image.crop.600x600 }}" alt="">
            </div>

            {%  if object.tag  %}
            <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>
                {{ object.tag }}
            </span></div>
            {% endif %}
            <div class="product_info">
                <h6 class="product_name"><a href="/">{{ object.name }} </a></h6>
                <div class="">Размерная сетка: <span>{{ object.size }} </span></div>
            </div>
        </div>
            <div class="red_button add_to_cart_button js-show-modal1" slug="{{ object.slug }}"><a href="#">Посмотреть</a></div>
        </div>




    {% endfor %}

            <!-- Modal1 -->
	<div class="wrap-modal1 js-modal1 p-t-60 p-b-20">
		<div class="overlay-modal1 js-hide-modal1"></div>

		<div class="container">
			<div class="bg0 p-t-60 p-b-30 p-lr-15-lg how-pos3-parent">
				<button class="how-pos3 hov3 trans-04 js-hide-modal1">
					<img src="{% static 'images/icons/icon-close.png' %}" alt="CLOSE">
				</button>
                <div class="row">
                    <div class="col-lg-8">
                        <div class="single_product_pics">
                            <div class="row">
                                <div class="col-lg-3 thumbnails_col order-lg-1 order-2">
                                    <div style="max-height:527px;height:auto;width:auto;overflow:scroll;">
                                    <div class="single_product_thumbnails">
                                        <ul id="imgList">
                                            <!--<li class="active"><img src="" id="img1" alt="" data-image=""></li>-->
                                        </ul>
                                    </div>
                                    </div>
                                </div>
                                <div class="col-lg-9 image_col order-lg-2 order-1">
                                    <div class="single_product_image">
                                        <div class="single_product_image_background" id="imgmain"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="product_details">
                            <div class="product_details_title">
                                <h3 class="cl1 bold " id="modal_name"></h3>
                                <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center" id="modal_tag" style="height: 29px; color: #fff; visibility: hidden;">
                                    <span>
                                    </span>
                                </div>

                                <h5 id="modal_content">{{ object.content }} </h5>
                            </div>

                            <div>
                                <div class="detail_container">
                                    <a href="/">Производитель:<span id="modal_manufacturer">&nbsp;</span></a>
                                </div>

                                <div class="detail_container">
                                    <a href="/">Пол:<span id="modal_sex">&nbsp;&nbsp;</span></a>
                                </div>

                                 <div class="detail_container">
                                    <a href="/">Цвет верха:<span id="modal_color">&nbsp;&nbsp;</span></a>
                                </div>

                                <div class="detail_container">
                                    <a href="/">Материал подкладки:<span id="modal_material_top">&nbsp;&nbsp; </span></a>
                                </div>

                                <div class="detail_container">
                                    <a href="/">Материал подошвы:<span id="modal_material_bottom">&nbsp;&nbsp; </span></a>
                                </div>



                                 <div class="detail_container">
                                    <a href="/">Размерный ряд:<span id="modal_size">&nbsp;&nbsp; </span></a>
                                </div>

                                 <div class="detail_container">
                                    <a href="/">Год коллекция:<span id="modal_year">&nbsp;</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>

</div>
{% if is_paginated %}
 {% if object_list %}
      <div class="row p-t-45">
      <div class="d-i-b" style="margin: auto">
        <ul class="pagination">

        {% if page_obj.has_previous %}
            <div id="" class="page_next">
                <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a>
            </div>
        {% else %}
            <div id="" class="page_next disabled">
               <i class="fa fa-chevron-left" aria-hidden="true"></i></a>
            </div>
{#            <li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>#}
        {% endif %}

        {% if page_obj.number|add:'-2' > 1 %}
            <li class="page_total "><a class="page_color" href="?page={{ page_obj.number|add:'-3' }}">&hellip;</a></li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page_current page_total"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
           {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
            <li><a class="page_total page_color" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}


        {% if page_obj.paginator.num_pages > page_obj.number|add:'2' %}
            <li class="page_total " ><a class="page_color" href="?page={{ page_obj.number|add:'3' }}">&hellip;</a></li>
        {% endif %}

        {% if page_obj.has_next %}
             <div id="next_page_1" class="page_next"  >
                <a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a>
            </div>
        {% else %}
            <li class="disabled page_next"  ><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
        {% endif %}

        </ul>
      </div>
      </div>

    {% endif %}
{% endif %}

</div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>

    $(document).ready(function(){
        $('.add_to_cart_button').click(function() {
          var _this = $(this);
          var slug = _this.attr("slug");
          $.ajax({
            url: '{% url 'catalogue:detail' %}',
            type: "get",
            data: {'slug': slug},

            success: function(data) {
                $(imgList).empty();
                $('.js-modal1').addClass('show-modal1');
                $('#modal_name').text(data.name);
                $('#modal_content').text(data.content);
                if (data.tag !== ""){
                    document.getElementById("modal_tag").style.visibility = "visible";
                    $('#modal_tag').text(data.tag);
                } else{
                    document.getElementById("modal_tag").style.visibility = "hidden";
                }
                $('#modal_manufacturer').text(data.manufacturer);
                $('#modal_sex').text(data.sex);
                $('#modal_color').text(data.color);
                $('#modal_material_top').text(data.material_top);
                $('#modal_material_bottom').text(data.material_bottom);
                $('#modal_size').text(data.size);
                $('#modal_year').text(data.year);

                url = 'url('+ data.img1+')';
                document.getElementById("imgmain").style.backgroundImage = url;





                if (data.img1!= null) {
                  $('#imgList').append(
                    $('<li class="">').append(
                        $('<img>').attr("id", "img1")
                          .attr("src", data.img1)
                          .attr("data-image", data.img1)
                ));
                }
                if (data.img2!= null) {
                  $('#imgList').append(
                    $('<li class="">').append(
                        $('<img>').attr("id", "img2")
                          .attr("src", data.img2)
                          .attr("data-image", data.img2)
                ));
                }
                if (data.img3!= null) {
                  $('#imgList').append(
                    $('<li class="">').append(
                        $('<img>').attr("id", "img3")
                          .attr("src", data.img3)
                          .attr("data-image", data.img3)
                ));
                }

                if (data.img4!= null) {
                  $('#imgList').append(
                    $('<li class="">').append(
                        $('<img>').attr("id", "img4")
                          .attr("src", data.img4)
                          .attr("data-image", data.img4)
                ));
                }



                if($('.single_product_thumbnails ul li').length)
                {
                    var thumbs = $('.single_product_thumbnails ul li');
                    var singleImage = $('.single_product_image_background');

                    thumbs.each(function()
                    {
                        var item = $(this);
                        item.on('click', function()
                        {
                            thumbs.removeClass('active');
                            item.addClass('active');
                            var img = item.find('img').data('image');
                            singleImage.css('background-image', 'url(' + img + ')');
                        });
                    });
                }


            },
            error: function(err) {
              console.log('error', err);
            }
          })
        })
    });
  </script>


<div class="m-t-100"></div>
<script src="{% static 'js/single_custom.js' %}"></script>


{% endblock %}



</body>
</html>

src/catalogue/templates/contact.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
</head>
<body >



{% block content %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/contact_styles.css' %}">
    <div class="container  m-t-20 ">

		<div class="col-lg-12 m-b-60">
            <div class="contact2_h1">КОНТАКТЫ</div>
            <div class="contact_h1">КОНТАКТЫ</div>
        </div>

		<!--<div class="text-center">-->
			<!--<h2>Контакты</h2>-->
		<!--</div>-->


		<div class="row background context_info ">

			<div class="col-lg-6 contact_col">
				<div class="contact_contents">
					<h1>Связь с нами</h1>
					<p>Вы можете связаться с нами любым доступным способом, представленным на этой странице.</p>
					<div>
						<p><i class="fa fa-map-marker" aria-hidden="true"></i>  Мясницкая ул. 13</p>
						<p><i class="fa fa-phone" aria-hidden="true"></i> +7-800-888-99-99</p>
						<p><i class="fa fa-envelope" aria-hidden="true"></i> info@tico-shoes.ru</p>
					</div>
					<div>
						<p>Часы работы: 8.00-20.00 Пн-Сб</p>
						<p>Воскресенье: 9.00-17.00</p>
					</div>
				</div>

				<div class="follow_us_contents">
					<h2>Следите за нами</h2>
					<ul class="social d-flex flex-row">
						<li><a href="#" style="background-color: #8f6247"><i class="fa fa-vk" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #3a61c9"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
						<li><a href="#" style="background-color: #8f6247"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>

					</ul>
				</div>

			</div>

			<div class="col-lg-6 get_in_touch_col">
				<div class="contact_contents">
					<h1>Есть вопрос?</h1>
					<p>Оставьте свой телефон и мы вам перезвоним</p>
					<form method="POST" class="send_message" action="{% url 'catalogue:contact_me' %}">
						<div>
							<input id="input_name" class="form_input input_name input_ph" type="text" name="name" placeholder="Имя" required="required" data-error="Укажите ваше имя.">
							<input id="input_email" class="form_input input_email input_ph" type="email" name="email" placeholder="E-mail" required="required" data-error="Укажите ваш e-mail.">
							<textarea id="content" class="input_ph input_message" name="content"  placeholder="Ваше сообщение или вопрос (можно не заполнять)" rows="3" required data-error="Напишите сообщение."></textarea>

                            <button id="review_submit" type="submit" class="red_button message_submit_btn trans_300" >Отправить</button>
                        </div>
					</form>
				</div>
			</div>

		</div>
	</div>


    <div class="m-t-100"></div>




    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript">
        var csrftoken = $("input[name=csrfmiddlewaretoken]").val();
        $(document).on('submit', '.send_message',function(e) {
            e.preventDefault();
            e.stopPropagation();
            var $form = $(this);
            var url = $form.attr( "action" );
            var thisId = $form.attr( "id" );
            $.post(url, $form.serialize())
                .done(function(data) {
                    swal("", "Сообщение успешно оставлено!!", "success");
                });
        });
    </script>



{% endblock %}


</body>
</html>